export const PATHS = {
  ROOT: '/',
  SWAP: '/swap',
  VAULT: '/vault',
  FRAKTIONALIZE: '/fraktionalize',
  WALLET: '/wallet',
  PAGE_404: '/404',
  COLLECTIONS: '/collections',
  COLLECTION: '/collection',
  VAULT_PUBKEY: '/:vaultPubkey',
  WALLET_PUBKEY: '/:walletPubkey',
  COLLECTION_NAME: '/:collectionName',
  EARN: '/earn',
  FRAKT: 'https://frakt.xyz/',
  TRADE: 'https://dex.fraktion.art/',
};
