export { default as Page404 } from './Page404';
export { default as SwapPage } from './SwapPage';
export { default as VaultsPage } from './VaultsPage';
export { default as VaultPage } from './VaultPage';
export { default as WalletPage } from './WalletPage';
export { default as FraktionalizePage } from './FraktionalizePage';
export { default as CollectionsPage } from './CollectionsPage';
export { default as CollectionPage } from './CollectionPage';
export { default as PoolsPage } from './PoolsPage';
